#ifndef DIALOG_H
#define DIALOG_H

#include <QDialog>
#include <QMap>
class Proxy;
namespace Ui {
  class dialog_null_systemSetDialog;
}
class dialog_null_editUserDialog;
class dialog_null_TipDialog;
class QComboBox;
class dialog_null_systemSetDialog : public QDialog
{
  Q_OBJECT

public:
  explicit dialog_null_systemSetDialog(QWidget *parent = 0);
  ~dialog_null_systemSetDialog();

  int getContentSize(){return content.size();}
private:
  void setComboValue(QString ,QString ,QComboBox *);

private: //xml
    void startXml(QString);
    void generalSubGeneral();
    void generalTime();
    void generalUser();
    void channelPreview();
    void channelStream();
    void channelVideoSet();
    void channelAudioSet();
    void networkWifi();
    void networkService();
    void networkWireless();
    void warnEmail();
    void warnMoveTest();
    void warnVideoLost();
    void warnDeviceWarn();
    void picManagerPicManager();
    void systemLog();
    void systemWeihu();
    void systemInfo();
    void otherMemory();
    void otherYuntai();
signals:
  void sendMessageToProxy(QString);
public slots:
 void recvMessageFromProxy(QString);
void getSender(); /*该函数确保前一个命令没有发送前，后一个命令不可用*/
  void curRow(int);
void pushButtonOtherYuntai();
void pushButtonOtherMemory();
void comboBoxMemoryDiskSize(int);
void comboBoxYuntaiChannelId(int);
void comboBoxYuntaiBaudRate(int);
void comboBoxYuntaiProtocol(int);
void comboBoxYuntaiAddr(int);
void checkBoxYuntaiLeftRightExchange(int);
void checkBoxYuntaiUpDownExchange(int);
void checkBoxYuntaiStopExchange(int);
void checkBoxYuntaiZoomedExchange(int);
void checkBoxYuntaiZoomExchange(int);
void pushButtonOtherUse();
void pushButtonOtherSure();
void pushButtonOtherCancel();
void pushButtonSystemInfo();
void pushButtonSystemLog();
void pushButtonSystemWeihu();
void comboBoxLogType(int);
void checkBoxLogDate(int);
void pushButtonLogBackupToU();
void checkBoxWeihuRestart(int);
void comboBoxWeihuUpdateType(int);
void comboBoxWeihuServer(int);
void pushButtonWeihuImportConfig();
void pushButtonWeihuExportConfig();
void pushButtonWeihuUpdate();
void pushButtonWeihuRegister();
void pushButtonWeihuFormatAll();
void pushButtonSystemSure();
void pushButtonSystemUse();
void pushButtonSystemCancel();
void pushButtonPicManagerPicManager();
void comboBoxPicManagerFindType(int);
void comboBoxPicManagerChannelId(int);
void pushButtonPicManagerSelectAll();
void pushButtonPicManagerDel();
void pushButtonPicManagerBackupToU();
void pushButtonPicManagerFind();
void pushButtonPicManagerSure();
void pushButtonPicManagerUse();
void pushButtonPicManagerCancel();
void pushButtonWarnDeviceWarn();
void pushButtonWarnVideoLost();
void pushButtonWarnMoveTest();
void pushButtonWarnEmail();
void pushButtonVideoLostSelectAll();
void pushButtonVideoLostDefault();
void pushButtonVideoLostWarnOut1();
void checkBoxVideoLostOpen1(int);
void checkBoxVideoLostWarnOrder1(int);
void pushButtonVideoLostWarnOut2();
void checkBoxVideoLostOpen2(int);
void checkBoxVideoLostWarnOrder2(int);
void pushButtonVideoLostWarnOut3();
void pushButtonVideoLostWarnOut4();
void checkBoxVideoLostWarnOrder4(int);
void checkBoxVideoLostOpen4(int);
void checkBoxVideoLostOpen3(int);
void checkBoxVideoLostWarnOrder3(int);
void pushButtonVideoLostWarnOut5();
void pushButtonVideoLostWarnOut6();
void checkBoxVideoLostWarnOrder6(int);
void checkBoxVideoLostOpen6(int);
void checkBoxVideoLostOpen5(int);
void checkBoxVideoLostWarnOrder5(int);
void pushButtonVideoLostWarnOut7();
void pushButtonVideoLostWarnOut8();
void checkBoxVideoLostWarnOrder8(int);
void checkBoxVideoLostOpen8(int);
void checkBoxVideoLostOpen7(int);
void checkBoxVideoLostWarnOrder7(int);
void pushButtonMoveTestSelectAll();
void pushButtonMoveTestDefault();
void checkBoxMoveTestOpen1(int);
void checkBoxMoveTestWarnOrder1(int);
void pushButtonMoveTestAreaSet1();
void pushButtonMoveTestWarnOut1();
void checkBoxMoveTestWarnOrder2(int);
void checkBoxMoveTestOpen2(int);
void pushButtonMoveTestAreaSet2();
void pushButtonMoveTestWarnOut2();
void checkBoxMoveTestWarnOrder3(int);
void checkBoxMoveTestOpen3(int);
void pushButtonMoveTestWarnOut3();
void pushButtonMoveTestAreaSet3();
void checkBoxMoveTestWarnOrder4(int);
void checkBoxMoveTestOpen4(int);
void pushButtonMoveTestWarnOut4();
void pushButtonMoveTestAreaSet4();
void checkBoxMoveTestWarnOrder5(int);
void checkBoxMoveTestOpen5(int);
void pushButtonMoveTestWarnOut5();
void pushButtonMoveTestAreaSet5();
void checkBoxMoveTestWarnOrder6(int);
void checkBoxMoveTestOpen6(int);
void pushButtonMoveTestWarnOut6();
void pushButtonMoveTestAreaSet6();
void checkBoxMoveTestWarnOrder7(int);
void checkBoxMoveTestOpen7(int);
void pushButtonMoveTestWarnOut7();
void pushButtonMoveTestAreaSet7();
void checkBoxMoveTestWarnOrder8(int);
void checkBoxMoveTestOpen8(int);
void pushButtonMoveTestWarnOut8();
void pushButtonMoveTestAreaSet8();
void pushButtonEmailAddList();
void pushButtonEmailEditList();
void pushButtonEmailDelList();
void pushButtonEmailServerPort();
void comboBoxEmailServer(int);
void comboBoxEmailSafeType(int);
void pushButtonEmailTest();
void pushButtonDeviceWarnSelectAll();
void pushButtonDeviceWarnDefault();
void checkBoxDeviceWarnOpen1(int);
void checkBoxDeviceWarnWarnOrder1(int);
void pushButtonDeviceWarnWarnOut1();
void comboBoxDeviceWarnFuncModel1(int);
void checkBoxDeviceWarnOpen2(int);
void checkBoxDeviceWarnWarnOrder2(int);
void comboBoxDeviceWarnFuncModel2(int);
void pushButtonDeviceWarnWarnOut2();
void checkBoxDeviceWarnWarnOrder4(int);
void checkBoxDeviceWarnOpen4(int);
void checkBoxDeviceWarnOpen3(int);
void checkBoxDeviceWarnWarnOrder3(int);
void comboBoxDeviceWarnFuncModel4(int);
void comboBoxDeviceWarnFuncModel3(int);
void pushButtonDeviceWarnWarnOut3();
void pushButtonDeviceWarnWarnOut4();
void checkBoxDeviceWarnWarnOrder6(int);
void checkBoxDeviceWarnOpen6(int);
void checkBoxDeviceWarnOpen5(int);
void checkBoxDeviceWarnWarnOrder5(int);
void comboBoxDeviceWarnFuncModel6(int);
void comboBoxDeviceWarnFuncModel5(int);
void pushButtonDeviceWarnWarnOut5();
void pushButtonDeviceWarnWarnOut6();
void checkBoxDeviceWarnWarnOrder8(int);
void checkBoxDeviceWarnOpen8(int);
void checkBoxDeviceWarnOpen7(int);
void checkBoxDeviceWarnWarnOrder7(int);
void comboBoxDeviceWarnFuncModel8(int);
void comboBoxDeviceWarnFuncModel7(int);
void pushButtonDeviceWarnWarnOut7();
void pushButtonDeviceWarnWarnOut8();
void pushButtonWarnSure();
void pushButtonWarnUse();
void pushButtonWarnCancel();
void pushButtonNetworkService();
void pushButtonNetworkWifi();
void pushButtonNetworkWireless();
void checkBoxWirelessDhcp(int);
void pushButtonWifiADSLConnect();
void pushButtonWifiADSLDisconnect();
void pushButtonWifiCardDisconnect();
void pushButtonWifiCardConnect();
void pushButtonNetworkCancel();
void pushButtonNetworkSure();
void pushButtonNetworkUse();
void pushButtonChannelStream();
void pushButtonChannelAudioSet();
void pushButtonChannelVideoSet();
void pushButtonChannelPreview();
void pushButtonVideoSetVideoCopy();
void pushButtonVideoSetDefault();
void checkBoxVideoSetMyselfVideo1(int);
void checkBoxVideoSetTimingVideoTwo1(int);
void checkBoxVideoSetTimingVideoOne1(int);
void checkBoxVideoSetMyselfVideo2(int);
void checkBoxVideoSetTimingVideoOne2(int);
void checkBoxVideoSetTimingVideoTwo2(int);
void checkBoxVideoSetMyselfVideo3(int);
void checkBoxVideoSetMyselfVideo4(int);
void checkBoxVideoSetTimingVideoOne3(int);
void checkBoxVideoSetTimingVideoTwo3(int);
void checkBoxVideoSetTimingVideoTwo4(int);
void checkBoxVideoSetTimingVideoOne4(int);
void checkBoxVideoSetMyselfVideo5(int);
void checkBoxVideoSetMyselfVideo6(int);
void checkBoxVideoSetTimingVideoOne5(int);
void checkBoxVideoSetTimingVideoTwo5(int);
void checkBoxVideoSetTimingVideoTwo6(int);
void checkBoxVideoSetTimingVideoOne6(int);
void checkBoxVideoSetMyselfVideo7(int);
void checkBoxVideoSetMyselfVideo8(int);
void checkBoxVideoSetTimingVideoOne7(int);
void checkBoxVideoSetTimingVideoTwo7(int);
void checkBoxVideoSetTimingVideoTwo8(int);
void checkBoxVideoSetTimingVideoOne8(int);
void comboBoxStreamMinorFenBianLv1(int);
void comboBoxStreamFenbialv1(int);
void comboBoxStreamLiuChangDu1(int);
void comboBoxStreamLiuChangDu2(int);
void comboBoxStreamMinorFenBianLv2(int);
void comboBoxStreamFenbialv2(int);
void comboBoxStreamFenbialv4(int);
void comboBoxStreamLiuChangDu4(int);
void comboBoxStreamLiuChangDu3(int);
void comboBoxStreamMinorFenBianLv4(int);
void comboBoxStreamMinorFenBianLv3(int);
void comboBoxStreamFenbialv3(int);
void comboBoxStreamFenbialv6(int);
void comboBoxStreamLiuChangDu6(int);
void comboBoxStreamLiuChangDu5(int);
void comboBoxStreamMinorFenBianLv6(int);
void comboBoxStreamMinorFenBianLv5(int);
void comboBoxStreamFenbialv5(int);
void comboBoxStreamFenbialv8(int);
void comboBoxStreamLiuChangDu8(int);
void comboBoxStreamLiuChangDu7(int);
void comboBoxStreamMinorFenBianLv8(int);
void comboBoxStreamMinorFenBianLv7(int);
void comboBoxStreamFenbialv7(int);
void pushButtonPreviewCopy();
void pushButtonPreviewSetDefault();
void pushButtonPreviewChannelSort();
void checkBoxPreviewArenHide1(int);
void pushButtonPreviewAreaHideSet1();
void checkBoxPreviewHide1(int);
void comboBoxPreviewOSD1(int);
void checkBoxPreviewArenHide2(int);
void pushButtonPreviewAreaHideSet2();
void checkBoxPreviewHide2(int);
void comboBoxPreviewOSD2(int);
void checkBoxPreviewArenHide3(int);
void pushButtonPreviewAreaHideSet3();
void checkBoxPreviewHide3(int);
void comboBoxPreviewOSD3(int);
void checkBoxPreviewArenHide4(int);
void pushButtonPreviewAreaHideSet4();
void checkBoxPreviewHide4(int);
void comboBoxPreviewOSD4(int);
void checkBoxPreviewArenHide5(int);
void pushButtonPreviewAreaHideSet5();
void checkBoxPreviewHide5(int);
void comboBoxPreviewOSD5(int);
void checkBoxPreviewArenHide6(int);
void pushButtonPreviewAreaHideSet6();
void checkBoxPreviewHide6(int);
void comboBoxPreviewOSD6(int);
void checkBoxPreviewArenHide7(int);
void pushButtonPreviewAreaHideSet7();
void checkBoxPreviewHide7(int);
void comboBoxPreviewOSD7(int);
void checkBoxPreviewArenHide8(int);
void pushButtonPreviewAreaHideSet8();
void checkBoxPreviewHide8(int);
void comboBoxPreviewOSD8(int);
void comboBoxAudioSetAudioZoom1(int);
void checkBoxAudioSetAudio1(int);
void comboBoxAudioSetBindVideo1(int);
void checkBoxAudioSetAudio2(int);
void comboBoxAudioSetBindVideo2(int);
void comboBoxAudioSetAudioZoom2(int);
void checkBoxAudioSetAudio3(int);
void comboBoxAudioSetBindVideo4(int);
void comboBoxAudioSetAudioZoom4(int);
void checkBoxAudioSetAudio4(int);
void comboBoxAudioSetBindVideo3(int);
void comboBoxAudioSetAudioZoom3(int);
void pushButtonChannelSure();
void pushButtonChannnelUse();
void pushButtonChannelCancel();
void pushButtonGeneralSubGeneral();
void pushButtonGeneralTime();
void pushButtonGeneralUser();
void comboBoxUserUserList(int);
void pushButtonUserUserAdd();
void pushButtonUserUserEdit();
void pushButtonUserUserDel();
void checkBoxSubGeneralGuide(int);
void comboBoxSubGeneralTransparent(int);
void comboBoxSubGeneralVGAResolutionRatio(int);
void comboBoxSubGeneralSensorData(int);
void checkBoxTimeAutoGetTime(int);
void comboBoxTimeTimeFormat(int);
void comboBoxTimeTimeArea(int);
void pushButtonGeneralSure();
void pushButtonGeneralCancel();
void pushButtonGeneralUse();



protected:
  bool eventFilter(QObject *, QEvent *);


private:
  void initWidget();
  void loadQssFile(QString fileName);

private:
  void testFile();
  void createFunctionAndConnection(QString);
private:
  Ui::dialog_null_systemSetDialog *ui;
  QString content;
  dialog_null_TipDialog *tDialog;
  Proxy *p;
  dialog_null_editUserDialog *editUser;
  QString senderName;
  QString oldMenu;
  bool use;
  QString messageContent;
  QMap<QString,QObject *> widgetMap;
  QVector<QWidget *> userName;

private:
  QString oldName;
};

#endif // DIALOG_H
